# Site settings
title: Alec G. Moore
email: agm (at) knights.ucf.edu


permalink: pretty

quote: > # this means to ignore newlines until "baseurl:"
  If experimenters have free will, then so do elementary particles. -John H. Conway
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tapiralec.github.io" # the base hostname & protocol for your site

about_author_snippet: >
  Alec Moore is a Ph.D. Candidate at The University of Central Florida. He received his M.S. in Computer Science in May 2016, as well as his B.S. in Physics and B.S. in Computer Science at The University of Texas at Dallas in May 2014.

about_author_snippet_for_posts: >
  Expressed opinions do not represent those of any employers.

# Social
twitter_username: tapiralec
github_username:  tapiralec
scholar_username: Xnrf710AAAAJ
scholar_citationname: Alec G. Moore
linkedin_username: alecgmoore

# Build settings
markdown: kramdown
